### PR TITLE
update version

### PR DESCRIPTION
**Pull request by kain88-de**

### CODE REVIEW

**Comment by marcelotrevisani** [comment]
@conda-forge-admin, please update circle

**Comment by marcelotrevisani** [comment]
Just one thing, I think you could remove the ``build.sh`` and modify your ``meta.yaml`` to:
```
build:
  script: python -m pip install --no-deps --ignore-installed .
  number: 0
  skip: True  # [win]
```

and add ``pip`` as build dependency.

**Comment by marcelotrevisani** [comment]
@conda-forge-admin , please rerender

**Comment by marcelotrevisani** [comment]
@conda-forge-admin, please add noarch: python

**Comment by marcelotrevisani** [comment]
I think you can remove the 
```
skip: true  # [win]
```
and let this as ``noarch: python``, lets see :)

**Comment by kain88-de** [comment]
Thanks for the help

> I think you could remove the build.sh and modify your meta.yaml to:

This is not possible. The `build.sh` script does more then just calling pip. Datreant.data depends on a namespace package and we need to clean up the installation for conda.


> and let this as noarch: python, lets see :)

Nope, this won't work. The package is currently not supported under windows. It relies on file-locks to allow multiprocessing, which is not supported under windows atm.  I'm aware of portalocker and similar packages offering file-locking in a cross-platform manner. The package still uses native solutions and hasn't been ported to windows.

**Comment by marcelotrevisani** [comment]
Got it.

The recommended way to install python packages in conda recipes is using pip as I described before, and you also can put two lines in your ``meta.yaml``, like:

```
build:
  script:
    - python -m pip install --no-deps --ignore-installed .
    - rm -f $SP_DIR/*-nspkg.pth
  number: 0
  skip: True  # [win]
```
or just update your ``build.sh``. However, for ``osx`` your package is running

**Comment by marcelotrevisani** [comment]
@conda-forge-admin, please update circle

**Comment by marcelotrevisani** [comment]
It seems the bot is not doing his job

**Comment by marcelotrevisani** [comment]
@conda-forge-admin-please-update-circle

**Comment by marcelotrevisani** [comment]
cc: @ocefpaf

**Comment by kain88-de** [comment]
@conda-forge-admin, please update circle

**Comment by kain88-de** [comment]
@conda-forge-admin, please rerender

**Comment by kain88-de** [comment]
@ocefpaf The circle CI runs really do not want to start on this repository for some reason

**Comment by ocefpaf** [comment]
> @ocefpaf The circle CI runs really do not want to start on this repository for some reason

If that is an expired token #7 should fix it. I'll re-start the CIs here in a moment.

**Comment by ocefpaf** [comment]
@kain88-de looks like someone is "following" the CircleCI project b/c the URL is 

https://circleci.com/gh/datreant/datreant.data-feedstock

instead of

https://circleci.com/gh/conda-forge/datreant.data-feedstock

**Comment by kain88-de** [comment]
What does following mean for circleCi? I know the github org and could
change things. I’m just not sure what.

**Comment by kain88-de** [comment]
ha found the solution. @ocefpaf you were right I needed to turn of builds for the datreant org on our clone of this repository. Thanks for the hint.

**Comment by ocefpaf** [comment]
>  @ocefpaf you were right I needed to turn of builds for the datreant org on our clone of this repository. Thanks for the hint.

Actually I believe that the conda-forge version of the CI was running when #7 executed the update. We were just not "seeing" it. However, due to the way CircleCI works, we recommend to deactivate the forks instances of the test like you did there.

**Pull request merged**
